apiVersion: v1
kind: Service
metadata:
  name: ci-svc-1
spec:
  clusterIP: None
  selector:
    app: ip-app-statefulset
  ports:
  - name: http
    port: 30002
    targetPort: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip-app-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app-statefulset
  template:
    metadata:
      labels:
        app: ip-app-statefulset
    spec:
      containers:
      - name: ip-app
        image: harshajain/ip_app
        ports:
        - containerPort: 8080
